select
    cd_remessa::bigint as cd_remessa,
    cd_reg::bigint as conta,
    cd_lancamento::bigint as cd_lancamento,
    cd_atendimento::bigint as cd_atendimento,
    cd_paciente::bigint as cd_paciente,
    nm_paciente,
    cd_prestador::bigint as cd_prestador,
    nm_prestador,
    cd_convenio::bigint as cd_convenio,
    cnpj_convenio,
    nm_convenio,
    tp_atendimento,
    upper(btrim(coalesce(nr_guia, ''))) as nr_guia_normalizada,
    regexp_replace(coalesce(nr_carteira, ''), '[^0-9]', '', 'g')::text as nr_carteira_normalizada_com_zero,
    ltrim(regexp_replace(coalesce(nr_carteira, ''), '[^0-9]', '', 'g'), '0') as nr_carteira_normalizada,
    upper(btrim(coalesce(cd_pro_fat, ''))) as cd_pro_fat_normalizado,
    upper(btrim(coalesce(cd_tuss, ''))) as cd_tuss_normalizado,
    descricao,
    dt_atendimento,
    dt_alta,
    dt_competencia,
    dt_lancamento,
    qt_lancamento,
    round(coalesce(vl_total_conta, 0)::numeric, 2) as valor_item,
    cd_gru_fat,
    ds_gru_fat,
    cd_gru_pro,
    ds_gru_pro
from {{ source('oracle_stage', 'ipm_itens_oracle') }}
